/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiumeetup;

import java.io.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class Studentframe extends javax.swing.JFrame {

    /**
     * Creates new form Studentframe
     */
    public Studentframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtassignment = new javax.swing.JTextField();
        CGPA = new javax.swing.JButton();
        ASSIGNMENT = new javax.swing.JButton();
        ROUTINE = new javax.swing.JButton();
        FACULTY = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        Detaisl = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        changepass = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        txtroutine = new javax.swing.JTextField();
        txtfaculty = new javax.swing.JTextField();
        txtass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        txtassignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtassignmentActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CGPA.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CGPA.setForeground(new java.awt.Color(255, 102, 0));
        CGPA.setText("CGPA");
        CGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGPAActionPerformed(evt);
            }
        });

        ASSIGNMENT.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ASSIGNMENT.setForeground(new java.awt.Color(255, 102, 0));
        ASSIGNMENT.setText("ASSIGNMENT");
        ASSIGNMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASSIGNMENTActionPerformed(evt);
            }
        });

        ROUTINE.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ROUTINE.setForeground(new java.awt.Color(255, 102, 0));
        ROUTINE.setText("ROUTINE");
        ROUTINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROUTINEActionPerformed(evt);
            }
        });

        FACULTY.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        FACULTY.setForeground(new java.awt.Color(255, 102, 0));
        FACULTY.setText("FACULTY");
        FACULTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACULTYActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        Detaisl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Detaisl.setForeground(new java.awt.Color(255, 102, 0));
        Detaisl.setText("DETAILS");
        Detaisl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetaislActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        changepass.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        changepass.setForeground(new java.awt.Color(255, 102, 0));
        changepass.setText("CHANGE PASSWORD");
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });

        LOGOUT.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 51, 0));
        LOGOUT.setText("LOG OUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        txtfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacultyActionPerformed(evt);
            }
        });

        jButton1.setText("edit subject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Detaisl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CGPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changepass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ASSIGNMENT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ROUTINE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FACULTY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addComponent(txtfaculty, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(txtass)
                            .addComponent(txtroutine)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ASSIGNMENT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtroutine, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ROUTINE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FACULTY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(txtass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Detaisl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changepass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGPAActionPerformed

      int id=CheckClass.getId();
      Student stu=new Student();
      //TransferData td=new TransferData();
      stu.id=id;
        
        try {
            stu=stu.getclass(stu.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      String cg=String.valueOf(stu.cgpa);
      txtarea.setText(cg);
      
      
        
        
        
    }//GEN-LAST:event_CGPAActionPerformed

    private void ASSIGNMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASSIGNMENTActionPerformed
       int id=CheckClass.getId();
       ArrayList<String> assign=new ArrayList<>();
       String set="";
      Student stu=new Student();
      stu.id=id;
     
        try {
            stu=stu.getclass(stu.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
      
          for(String key: stu.ass.keySet()){
            set=set+("Subject "+key+" assignment"+stu.ass.get(key)+"\n");
        }
      txtarea.setText(set);
    }//GEN-LAST:event_ASSIGNMENTActionPerformed

    private void ROUTINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROUTINEActionPerformed
   
         int id=CheckClass.getId();
      Student stu=new Student();
      stu.id=id;
      
        try {
            stu=stu.getclass(stu.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
      txtarea.setText(stu.routine);
      
    }//GEN-LAST:event_ROUTINEActionPerformed

    private void FACULTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACULTYActionPerformed
     
        
         
        int id=CheckClass.getId();
      Student stu=new Student();
      stu.id=id;
      //TransferData td=new TransferData();
        try {
            stu=stu.getclass(stu.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
       txtarea.setText(stu.faculty);
        
    }//GEN-LAST:event_FACULTYActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        //new editrtn().setVisible(true);
        int id=CheckClass.getId();
        Student stu=new Student();
        try {
            stu=stu.getclass(id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        stu.setFaculty(txtfaculty.getText());
        try {
            stu.write(stu);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new mainmenu().setVisible(true);
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int id=CheckClass.getId();
        Student stu=new Student();
        try {
            stu=stu.getclass(id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        stu.setAssignment(txtroutine.getText());
        try {
            stu.write(stu);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DetaislActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetaislActionPerformed
        int id=CheckClass.getId();
      Student stu=new Student();
      stu.id=id;
      //TransferData td=new TransferData();
        try {
            stu=stu.getclass(stu.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      txtarea.setText(stu.toString());
    }//GEN-LAST:event_DetaislActionPerformed

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
        new stuPassChange().setVisible(true);
        
      
      
      
        
    }//GEN-LAST:event_changepassActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int id=CheckClass.getId();
        Student stu=new Student();
        try {
            stu=stu.getclass(id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        stu.setAssignment(txtass.getText());
        try {
            stu.write(stu);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacultyActionPerformed

    private void txtassignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtassignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtassignmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new stuSubjectedit().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ASSIGNMENT;
    private javax.swing.JButton CGPA;
    private javax.swing.JButton Detaisl;
    private javax.swing.JButton FACULTY;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton ROUTINE;
    private javax.swing.JButton changepass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtass;
    private javax.swing.JTextField txtassignment;
    private javax.swing.JTextField txtfaculty;
    private javax.swing.JTextField txtroutine;
    // End of variables declaration//GEN-END:variables
}
