/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiumeetup;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import uiumeetup.CheckClass;
import uiumeetup.Student;
import uiumeetup.Studentframe;

/**
 *
 * @author Asus
 */
public class Teacherframe extends javax.swing.JFrame {

    /**
     * Creates new form Teacherframe
     */
    public Teacherframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Routine = new javax.swing.JButton();
        COURSES = new javax.swing.JButton();
        COUNSELINGHOUR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        DEPARTMENT = new javax.swing.JButton();
        EDITROUTINE = new javax.swing.JButton();
        DESIGNATION = new javax.swing.JButton();
        CHANGEPASS = new javax.swing.JButton();
        DETAILS = new javax.swing.JButton();
        txtroutine = new javax.swing.JTextField();
        editcourse = new javax.swing.JButton();
        editcounseling = new javax.swing.JButton();
        crs = new javax.swing.JTextField();
        hr = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        editdesignation = new javax.swing.JButton();
        desig = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Routine.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Routine.setForeground(new java.awt.Color(255, 102, 0));
        Routine.setText("ROUTINE");
        Routine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoutineActionPerformed(evt);
            }
        });

        COURSES.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        COURSES.setForeground(new java.awt.Color(255, 102, 0));
        COURSES.setText("COURSES");
        COURSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COURSESActionPerformed(evt);
            }
        });

        COUNSELINGHOUR.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        COUNSELINGHOUR.setForeground(new java.awt.Color(255, 102, 0));
        COUNSELINGHOUR.setText("COUNSELING HOUR");
        COUNSELINGHOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COUNSELINGHOURActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        DEPARTMENT.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DEPARTMENT.setForeground(new java.awt.Color(255, 102, 0));
        DEPARTMENT.setText("DEPARTMENT");
        DEPARTMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPARTMENTActionPerformed(evt);
            }
        });

        EDITROUTINE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EDITROUTINE.setText("EDIT");
        EDITROUTINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITROUTINEActionPerformed(evt);
            }
        });

        DESIGNATION.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DESIGNATION.setForeground(new java.awt.Color(255, 102, 0));
        DESIGNATION.setText("DESIGNATION");
        DESIGNATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESIGNATIONActionPerformed(evt);
            }
        });

        CHANGEPASS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CHANGEPASS.setForeground(new java.awt.Color(255, 102, 0));
        CHANGEPASS.setText("CHANGE PASSWORD");
        CHANGEPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGEPASSActionPerformed(evt);
            }
        });

        DETAILS.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DETAILS.setForeground(new java.awt.Color(255, 102, 0));
        DETAILS.setText("DETAILS");
        DETAILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETAILSActionPerformed(evt);
            }
        });

        editcourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editcourse.setText("EDIT");
        editcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcourseActionPerformed(evt);
            }
        });

        editcounseling.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editcounseling.setText("EDIT");
        editcounseling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcounselingActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 51, 0));
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        editdesignation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editdesignation.setText("EDIT");
        editdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdesignationActionPerformed(evt);
            }
        });

        jButton1.setText("ADD ASSIGNMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DETAILS, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CHANGEPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Routine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DEPARTMENT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(COURSES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DESIGNATION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(COUNSELINGHOUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(editcourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editcounseling, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(editdesignation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EDITROUTINE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(crs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(desig, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hr)
                                            .addComponent(txtroutine)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Routine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtroutine, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EDITROUTINE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DEPARTMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(COURSES, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DESIGNATION, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desig, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hr)
                    .addComponent(editcounseling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(COUNSELINGHOUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(DETAILS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CHANGEPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EDITROUTINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITROUTINEActionPerformed
        // TODO add your handling code here:
        int id=CheckClass.getId();
        teacher tea=new teacher();
        tea.id=id;
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        tea.setRoutine(txtroutine.getText());
        try {
            tea.write(tea);
        } catch (IOException ex) {
            Logger.getLogger(Teacherframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                         
        
    }//GEN-LAST:event_EDITROUTINEActionPerformed

    private void RoutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoutineActionPerformed
        // TODO add your handling code here:
        int id=CheckClass.getId();
      teacher tea=new teacher();
      tea.id=id;
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
      txtArea.setText(tea.routine);
      
              
    }//GEN-LAST:event_RoutineActionPerformed

    private void DETAILSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETAILSActionPerformed
        // TODO add your handling code here:
        int id=CheckClass.getId();
     teacher tea=new teacher();
      tea.id=id;
      //TransferData td=new TransferData();
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      txtArea.setText(tea.toString());
    }//GEN-LAST:event_DETAILSActionPerformed

    private void CHANGEPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGEPASSActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new teaPassChange().setVisible(true);
    }//GEN-LAST:event_CHANGEPASSActionPerformed

    private void DEPARTMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPARTMENTActionPerformed
        // TODO add your handling code here:
         int id=CheckClass.getId();
     teacher tea=new teacher();
      tea.id=id;
      //TransferData td=new TransferData();
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      txtArea.setText(tea.department);
    }//GEN-LAST:event_DEPARTMENTActionPerformed

    private void COURSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COURSESActionPerformed
        // TODO add your handling code here:
         int id=CheckClass.getId();
     teacher tea=new teacher();
      tea.id=id;
      //TransferData td=new TransferData();
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      txtArea.setText(tea.course);
        
    }//GEN-LAST:event_COURSESActionPerformed

    private void DESIGNATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESIGNATIONActionPerformed
        // TODO add your handling code here:
         int id=CheckClass.getId();
     teacher tea=new teacher();
      tea.id=id;
      //TransferData td=new TransferData();
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      txtArea.setText(tea.designation);
    }//GEN-LAST:event_DESIGNATIONActionPerformed

    private void COUNSELINGHOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COUNSELINGHOURActionPerformed
        // TODO add your handling code here:
         int id=CheckClass.getId();
     teacher tea=new teacher();
      tea.id=id;
      //TransferData td=new TransferData();
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      txtArea.setText(tea.counseling_hour);
      
      
      
    }//GEN-LAST:event_COUNSELINGHOURActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new mainmenu().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void editcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcourseActionPerformed
        // TODO add your handling code here:
        int id=CheckClass.getId();
        teacher tea=new teacher();
        tea.id=id;
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        tea.setCourse(crs.getText());
        try {
            tea.write(tea);
        } catch (IOException ex) {
            Logger.getLogger(Teacherframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editcourseActionPerformed

    private void editdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdesignationActionPerformed
        // TODO add your handling code here:int id=CheckClass.getId();
         int id=CheckClass.getId();
        teacher tea=new teacher();
        tea.id=id;
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        tea.setDesignation(desig.getText());
        try {
            tea.write(tea);
        } catch (IOException ex) {
            Logger.getLogger(Teacherframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editdesignationActionPerformed

    private void editcounselingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcounselingActionPerformed
        // TODO add your handling code here:int id=CheckClass.getId();
        int id=CheckClass.getId();
        teacher tea=new teacher();
        tea.id=id;
        try {
            tea=tea.getclass(tea.id);
        } catch (Exception ex) {
            Logger.getLogger(Studentframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        tea.setCounseling_hour(hr.getText());
        try {
            tea.write(tea);
        } catch (IOException ex) {
            Logger.getLogger(Teacherframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editcounselingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new tea().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacherframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacherframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacherframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacherframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacherframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHANGEPASS;
    private javax.swing.JButton COUNSELINGHOUR;
    private javax.swing.JButton COURSES;
    private javax.swing.JButton DEPARTMENT;
    private javax.swing.JButton DESIGNATION;
    private javax.swing.JButton DETAILS;
    private javax.swing.JButton EDITROUTINE;
    private javax.swing.JButton Routine;
    private javax.swing.JTextField crs;
    private javax.swing.JTextField desig;
    private javax.swing.JButton editcounseling;
    private javax.swing.JButton editcourse;
    private javax.swing.JButton editdesignation;
    private javax.swing.JTextField hr;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtroutine;
    // End of variables declaration//GEN-END:variables
}
